app:
  http-status:
    requ-error: {
      400: 'Bad Request/错误请求',
      401: 'Unauthorized/未授权',
      403: 'Forbidden/禁止',
      404: 'Not Found/未找到',
      405: 'Method Not Allowed/方法未允许',
      406: 'Not Acceptable/无法访问',
      407: 'Proxy Authentication Required/代理服务器认证要求',
      408: 'Request Timeout/请求超时',
      409: 'Conflict/冲突',
      410: 'Gone/已经不存在',
      411: 'Length Required/需要数据长度',
      412: 'Precondition Failed/先决条件错误',
      413: 'Request Entity Too Large/请求实体过大',
      414: 'Request URI Too Long/请求URI过长',
      415: 'Unsupported Media Type/不支持的媒体格式',
      416: 'Requested Range Not Satisfiable/请求范围无法满足',
      417: 'Expectation Failed/期望失败'
    }
    resp-error: {
      500: 'Internal Server Error/内部服务器错误',
      501: 'Not Implemented/未实现',
      502: 'Bad Gateway/错误的网关',
      503: 'Service Unavailable/服务无法获得',
      504: 'Gateway Timeout/网关超时',
      505: 'HTTP Version Not Supported/不支持的 HTTP 版本'
    }

  sample-json-api: "https://gs.amac.org.cn/amac-infodisc/api/pof/manager/query"
  sample-html-api: "https://gs.amac.org.cn/amac-infodisc/res/pof/manager/%(id)s.html"
