CRAWLER:
  TITLE: '私募基金相关机构公示信息'
  TASKS:
    - AMAC-POF-ORG # 私募基金相关机构公示信息-私募基金机构
    - AMAC-POF-OFF # 私募基金相关机构公示信息-注销机构
    - AMAC-POF-ABNORMAL # 私募基金相关机构公示信息-异常机构
    - AMAC-POF-MESSING # 私募基金相关机构公示信息-失联机构
    - AMAC-POF-AGENCY # 私募基金相关机构公示信息-服务机构

  AMAC-POF-ORG:
    TITLE: '私募基金相关机构公示信息-私募基金机构-列表'
    URL: 'https://gs.amac.org.cn/amac-infodisc/api/pof/manager/query'
    METHOD: POST # POST | GET
    DATA-TYPE: JSON # JSON | HTML
    PAGINATION: True
    PAGINATION-PAGE: 0
    PAGINATION-SIZE: 100
    PARAMS: { 'page': '%(page)s', 'size': '%(size)s', 'timestamp': '%(timestamp)s' }
    PAYLOAD: { }
    DATA-MAPPER: 'content'
    DATA-TOTAL-MAPPER: 'totalElements'
    DATA-CONVERT: { 'TIMESTAMP': { 'establishDate': 'MILLISECOND', 'registerDate': 'MILLISECOND' } }
    DB-TABLE: 'AMAC_POF_ORG'
    DB-MAPPING: {
      'id': 'AMAC_ID',
      'managerName': 'MANA_NM',
      'artificialPersonName': 'ART_PER_NM',
      'registerNo': 'REG_NO',
      'establishDate': 'EST_DATE',
      'managerHasProduct': 'HAS_PROD',
      'url': 'DE_URL',
      'registerDate': 'REG_DATE',
      'registerAddress': 'REG_ADR',
      'registerProvince': 'REG_PRO',
      'registerCity': 'REG_CTY',
      'regAdrAgg': 'REG_ADR_AGG',
      'officeAdrAgg': 'OFF_ADR_AGG',
      'fundCount': 'FUND_NUM',
      'paidInCapital': 'PIC',
      'subscribedCapital': 'SC',
      'hasSpecialTips': 'HAS_SPE_TIP',
      'hasCreditTips': 'HAS_CRE_TIP',
      'regCoordinate': 'REG_LO_LA',
      'officeCoordinate': 'OFF_LO_LA',
      'officeAddress': 'OFF_ADR',
      'officeProvince': 'OFF_PRO',
      'officeCity': 'OFF_CTY',
      'primaryInvestType': 'PRI_IV_TYPE',
      'memberType': 'MEB_TYPE',
      'orgForm': 'ORG_FORM'
    }

  AMAC-POF-OFF:
    TITLE: '私募基金相关机构公示信息-注销机构-列表'
    URL: 'https://gs.amac.org.cn/amac-infodisc/api/cancelled/manager'
    METHOD: POST # POST | GET
    DATA-TYPE: JSON # JSON | HTML
    PAGINATION: True
    PAGINATION-PAGE: 0
    PAGINATION-SIZE: 100
    PARAMS: { 'page': '%(page)s', 'size': '%(size)s', 'timestamp': '%(timestamp)s' }
    PAYLOAD: { }
    DATA-MAPPER: 'content'
    DATA-TOTAL-MAPPER: 'totalElements'
    DATA-CONVERT: { 'TIMESTAMP': { 'establishmentTime': 'MILLISECOND', 'orgSignDate': 'MILLISECOND', 'cancelDate': 'MILLISECOND' } }
    DB-TABLE: 'AMAC_POF_OFF'
    DB-MAPPING: {
      'userTenantId': 'AMAC_ID',
      'orgName': 'ORG_NM',
      'orgCode': 'UNI_SOCIAL_CD',
      'establishmentTime': 'EST_DATE',
      'orgSignDate': 'REG_DATE',
      'cancelDate': 'CNL_DATE',
      'status': 'CNL_TYPE_CODE'
    }

  AMAC-POF-ABNORMAL:
    TITLE: '私募基金相关机构公示信息-异常机构-列表'
    URL: 'https://www.amac.org.cn/portal/front/abnormalOrg/getAbnormalOrgs'
    METHOD: GET # POST | GET
    DATA-TYPE: JSON # JSON | HTML
    PAGINATION: True
    PAGINATION-PAGE: 1
    PAGINATION-SIZE: 100
    PARAMS: { 'page': '%(page)s', 'size': '%(size)s', 'timestamp': '%(timestamp)s' }
    # PAYLOAD: { } # GET NONE REQUEST PAYLOAD
    DATA-MAPPER: 'data.data.dataList'
    DATA-TOTAL-MAPPER: 'data.data.total'
    DATA-CONVERT: { }
    DB-TABLE: 'AMAC_POF_ABNORMAL'
    DB-MAPPING: { 'org_name': 'ORG_NM', 'pcode': 'REG_NO', 'day_tobe_abnormal': 'ABNORMAL_DATE' }

  AMAC-POF-MESSING:
    TITLE: '私募基金相关机构公示信息-失联机构-列表'
    URL: 'https://www.amac.org.cn/portal/front/missingOrg/getMissingOrgs'
    METHOD: GET # POST | GET
    DATA-TYPE: JSON # JSON | HTML
    PAGINATION: True
    PAGINATION-PAGE: 1
    PAGINATION-SIZE: 100
    PARAMS: { 'page': '%(page)s', 'size': '%(size)s', 'timestamp': '%(timestamp)s' }
    # PAYLOAD: { } # GET NONE REQUEST PAYLOAD
    DATA-MAPPER: 'data.data.dataList'
    DATA-TOTAL-MAPPER: 'data.data.total'
    DATA-CONVERT: { }
    DB-TABLE: 'AMAC_POF_MISSING'
    DB-MAPPING: { 'org_name': 'ORG_NM', 'pcode': 'REG_NO', 'day_tobe_missing': 'MISSING_DATE' }

  AMAC-POF-AGENCY: