-- 私募基金管理人公示表
DROP TABLE IF EXISTS `AMAC_POF_ORG`;
CREATE TABLE `AMAC_POF_ORG`
(
    `ID`          VARCHAR(32) NOT NULL DEFAULT '1' COMMENT 'ID',
    `STATE`       VARCHAR(10) NOT NULL DEFAULT 'OK' COMMENT '数据状态：OK,DELETE,EXPIRED',
    `CREATE_TIME` DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '数据更新时间',
    `UPDATE_TIME` DATETIME             DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '数据创建时间',
    `POSITION`    INT                  DEFAULT 0 COMMENT '爬虫内容定位序列',
    `AMAC_ID`     VARCHAR(32)          DEFAULT NULL COMMENT 'AMAC ID',
    `MANA_NM`     VARCHAR(150)         DEFAULT NULL COMMENT '私募基金管理人名称',
    `ART_PER_NM`  VARCHAR(50)          DEFAULT NULL COMMENT '法定代表人/执行事务合伙人(委派代表)姓名',
    `REG_NO`      VARCHAR(20)          DEFAULT NULL COMMENT '登记编号',
    `EST_DATE`    DATE                 DEFAULT NULL COMMENT '成立时间',
    `HAS_PROD`    TINYINT              DEFAULT NULL COMMENT '是否有产品 0:否 1:是',
    `DE_URL`      VARCHAR(50)          DEFAULT NULL COMMENT '详情页URL',
    `REG_DATE`    DATE                 DEFAULT NULL COMMENT '登记时间',
    `REG_ADR`     VARCHAR(255)         DEFAULT NULL COMMENT '注册详细地址',
    `REG_PRO`     VARCHAR(50)          DEFAULT NULL COMMENT '注册省',
    `REG_CTY`     VARCHAR(50)          DEFAULT NULL COMMENT '注册市',
    `REG_ADR_AGG` VARCHAR(50)          DEFAULT NULL COMMENT '注册地（省）',
    `OFF_ADR_AGG` VARCHAR(50)          DEFAULT NULL COMMENT '办公地点（省）',
    `FUND_NUM`    INT                  DEFAULT NULL COMMENT '在管基金数量',
    `PIC`         DECIMAL(16, 4)       DEFAULT NULL COMMENT '实收资本',
    `SC`          DECIMAL(16, 4)       DEFAULT NULL COMMENT '认缴资本',
    `HAS_SPE_TIP` TINYINT              DEFAULT NULL COMMENT '是否有提示信息 0:否 1:是',
    `HAS_CRE_TIP` TINYINT              DEFAULT NULL COMMENT '是否有诚信信息 0:否 1:是',
    `REG_LO_LA`   VARCHAR(50)          DEFAULT NULL COMMENT '注册地坐标（经纬度）',
    `OFF_LO_LA`   VARCHAR(50)          DEFAULT NULL COMMENT '办公地坐标（经纬度）',
    `OFF_ADR`     VARCHAR(255)         DEFAULT NULL COMMENT '办公详细地址',
    `OFF_PRO`     VARCHAR(50)          DEFAULT NULL COMMENT '办公地所在省份',
    `OFF_CTY`     VARCHAR(50)          DEFAULT NULL COMMENT '办公地所在城市',
    `PRI_IV_TYPE` VARCHAR(50)          DEFAULT NULL COMMENT '机构类型',
    `MEB_TYPE`    VARCHAR(50)          DEFAULT NULL COMMENT '会员类型',
    `ORG_FORM`    VARCHAR(50)          DEFAULT NULL COMMENT '组织类型',
    PRIMARY KEY (`ID`)
) ENGINE = INNODB
  DEFAULT CHARSET = UTF8MB4
  COLLATE = UTF8MB4_GENERAL_CI COMMENT ='AMAC - 私募基金相关机构公示信息 - 私募基金管理机构信息表';

DROP TRIGGER IF EXISTS `AMAC_POF_ORG_GUID`;
CREATE TRIGGER `AMAC_POF_ORG_GUID`
    BEFORE INSERT
    ON `AMAC_POF_ORG`
    FOR EACH ROW
BEGIN
    IF NEW.ID = '1' THEN
        SET NEW.ID = (SELECT UUID_SHORT());
    END IF;
END;

-- 已注销私募基金管理人
DROP TABLE IF EXISTS AMAC_POF_OFF;
CREATE TABLE `AMAC_POF_OFF`
(
    `ID`            VARCHAR(32) NOT NULL DEFAULT '1' COMMENT 'ID',
    `STATE`         VARCHAR(10) NOT NULL DEFAULT 'OK' COMMENT '数据状态：OK,DELETE,EXPIRED',
    `CREATE_TIME`   DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '数据更新时间',
    `UPDATE_TIME`   DATETIME             DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '数据创建时间',
    `POSITION`      INT                  DEFAULT 0 COMMENT '爬虫内容定位序列',
    `AMAC_ID`       VARCHAR(32)          DEFAULT NULL COMMENT 'AMAC ID',
    `ORG_NM`        VARCHAR(150)         DEFAULT NULL COMMENT '管理人名称',
    `UNI_SOCIAL_CD` VARCHAR(50)          DEFAULT NULL COMMENT '统一社会信用代码',
    `EST_DATE`      DATE                 DEFAULT NULL COMMENT '成立时间',
    `REG_DATE`      DATE                 DEFAULT NULL COMMENT '登记时间',
    `CNL_DATE`      DATE                 DEFAULT NULL COMMENT '注销时间',
    `CNL_TYPE_CODE` VARCHAR(50)          DEFAULT NULL COMMENT '注销类型 100:主动注销 200:依公告注销 300:协会注销',
    PRIMARY KEY (`ID`)
) ENGINE = INNODB
  DEFAULT CHARSET = UTF8MB4
  COLLATE = UTF8MB4_GENERAL_CI COMMENT ='AMAC - 私募基金相关机构公示信息 - 已注销机构信息表';

DROP TRIGGER IF EXISTS `AMAC_POF_OFF_GUID`;
CREATE TRIGGER `AMAC_POF_OFF_GUID`
    BEFORE INSERT
    ON `AMAC_POF_OFF`
    FOR EACH ROW
BEGIN
    IF NEW.ID = '1' THEN
        SET NEW.ID = (SELECT UUID_SHORT());
    END IF;
END;

-- 异常经营机构信息表
DROP TABLE IF EXISTS `AMAC_POF_ABNORMAL`;
CREATE TABLE `AMAC_POF_ABNORMAL`
(
    `ID`            VARCHAR(32) NOT NULL DEFAULT '1' COMMENT 'ID',
    `STATE`         VARCHAR(10) NOT NULL DEFAULT 'OK' COMMENT '数据状态：OK,DELETE,EXPIRED',
    `CREATE_TIME`   DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '数据更新时间',
    `UPDATE_TIME`   DATETIME             DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '数据创建时间',
    `POSITION`      INT                  DEFAULT 0 COMMENT '爬虫内容定位序列',
    `ORG_NM`        VARCHAR(150)         DEFAULT NULL COMMENT '机构名称',
    `REG_NO`        VARCHAR(20)          DEFAULT NULL COMMENT '登记编号',
    `ABNORMAL_DATE` DATE                 DEFAULT NULL COMMENT '机构列入异常经营时间',
    PRIMARY KEY (`ID`)
) ENGINE = INNODB
  DEFAULT CHARSET = UTF8MB4
  COLLATE = UTF8MB4_GENERAL_CI COMMENT ='AMAC - 私募基金相关机构公示信息 - 异常机构信息表';

DROP TRIGGER IF EXISTS `AMAC_POF_ABNORMAL_GUID`;
CREATE TRIGGER `AMAC_POF_ABNORMAL_GUID`
    BEFORE INSERT
    ON `AMAC_POF_ABNORMAL`
    FOR EACH ROW
BEGIN
    IF NEW.ID = '1' THEN
        SET NEW.ID = (SELECT UUID_SHORT());
    END IF;
END;


-- 失联经营机构信息表
DROP TABLE IF EXISTS `AMAC_POF_MISSING`;
CREATE TABLE `AMAC_POF_MISSING`
(
    `ID`           VARCHAR(32) NOT NULL DEFAULT '1' COMMENT 'ID',
    `STATE`        VARCHAR(10) NOT NULL DEFAULT 'OK' COMMENT '数据状态：OK,DELETE,EXPIRED',
    `CREATE_TIME`  DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '数据更新时间',
    `UPDATE_TIME`  DATETIME             DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '数据创建时间',
    `POSITION`     INT                  DEFAULT 0 COMMENT '爬虫内容定位序列',
    `ORG_NM`       VARCHAR(150)         DEFAULT NULL COMMENT '机构名称',
    `REG_NO`       VARCHAR(20)          DEFAULT NULL COMMENT '登记编号',
    `MISSING_DATE` DATE                 DEFAULT NULL COMMENT '机构列入失联公示时间',
    PRIMARY KEY (`ID`)
) ENGINE = INNODB
  DEFAULT CHARSET = UTF8MB4
  COLLATE = UTF8MB4_GENERAL_CI COMMENT ='AMAC - 私募基金相关机构公示信息 - 失联经营机构信息表';

DROP TRIGGER IF EXISTS `AMAC_POF_MISSING_GUID`;
CREATE TRIGGER `AMAC_POF_MISSING_GUID`
    BEFORE INSERT
    ON `AMAC_POF_MISSING`
    FOR EACH ROW
BEGIN
    IF NEW.ID = '1' THEN
        SET NEW.ID = (SELECT UUID_SHORT());
    END IF;
END;