CREATE TABLE SAMPLE
(
    ID          INT AUTO_INCREMENT
        PRIMARY KEY,
    NAME        VARCHAR(20)                         NULL,
    AGE         INT                                 NULL,
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_TIME DATETIME  DEFAULT CURRENT_TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP
);
